name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        
      - name: Build
        run: bun run build
        
      - name: Prepare built branch
        run: |
          git fetch origin built || git checkout --orphan built
          git reset --hard
          git checkout main -- index.html styles dist
          git rm -rf --cached .
          git add dist index.html styles
        
      - name: Commit and push to built branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Built repo" || echo "No changes to commit"
          git push -f origin HEAD:built